sync_tokens = {";", "fimse", "fim", "$"}

# regras de produção
mgolgrammar = {
    "0": {"left":"P'", "right":("P",)},
    "1": {"left":"P", "right":("inicio", "V", "A",)},
    "2": {"left":"V", "right":("varinicio", "LV",)},
    "3": {"left":"LV", "right":("D", "LV",)},
    "4": {"left":"LV", "right":("varfim", ";",)},
    "5": {"left":"D", "right":("id", "TIPO", ";",)},
    "6": {"left":"TIPO", "right":("inteiro",)},
    "7": {"left":"TIPO", "right":("real",)},
    "8": {"left":"TIPO", "right":("literal",)},
    "9": {"left":"A", "right":("ES", "A",)},
    "10": {"left":"ES", "right":("leia", "id", ";",)},
    "11": {"left":"ES", "right":("escreva", "ARG", ";",)},
    "12": {"left":"ARG", "right":("literal",)},
    "13": {"left":"ARG", "right":("num",)},
    "14": {"left":"ARG", "right":("id",)},
    "15": {"left":"A", "right":("CMD", "A",)},
    "16": {"left":"CMD", "right":("id", "rcb", "LD", ";",)},
    "17": {"left":"LD", "right":("OPRD", "opm", "OPRD",)},
    "18": {"left":"LD", "right":("OPRD",)},
    "19": {"left":"OPRD", "right":("id",)},
    "20": {"left":"OPRD", "right":("num",)},
    "21": {"left":"A", "right":("COND", "A",)},
    "22": {"left":"COND", "right":("CABEÇALHO", "CORPO",)},
    "23": {"left":"CABEÇALHO", "right":("se", "(", "EXP_R", ")", "entao",)},
    "24": {"left":"EXP_R", "right":("OPRD", "opr", "OPRD",)},
    "25": {"left":"CORPO", "right":("ES", "CORPO",)},
    "26": {"left":"CORPO", "right":("CMD", "CORPO",)},
    "27": {"left":"CORPO", "right":("COND", "CORPO",)},
    "28": {"left":"CORPO", "right":("fimse",)},
    "29": {"left":"A", "right":("fim",)},
}